name: Optimize jpg files

on:
  pull_request:
    branches:
      - master
    paths:
      - '**.jpg'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 2
      
      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@24d32ffd492484c1d75e0c0b894501ddb9d30d62 # v47.0.0

      - name: Install jpegoptim
        run: sudo apt-get install -y jpegoptim

      - name: List all changed files
        env:
          CHANGED: ${{ steps.changed-files.outputs.added_files }}
        run: |
          for file in $CHANGED; do
            if [[ "$file" = *".jpg"* ]]; then
              echo "Trying to optimize $file"
              jpegoptim "$file"
            fi
          done

      - uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: Apply jpegoptim changes
